/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.BalanceGeneralControlador;
import Controlador.BalanzaComprobacionControlador;
import Controlador.EstadoDeResultadoControlador;
import Controlador.LibroMayorControlador;
import Utilidades.Fondo;
import static java.lang.System.exit;
import javax.swing.JFrame;

/**
 *
 * @author Gaby Laínez
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
         this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.escritorio.setBorder(new Fondo("/imagenes/f2.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FondoJscroll = new javax.swing.JPanel();
        BtnBalanzaComprobacion = new newscomponents.RSButtonFlat_new();
        BtnEstadoResultado = new newscomponents.RSButtonFlat_new();
        BtnBalanzaGeneral = new newscomponents.RSButtonFlat_new();
        BtnPartidaAjuste = new newscomponents.RSButtonFlat_new();
        BtnPartidasCierre = new newscomponents.RSButtonFlat_new();
        BtnCierreContable = new newscomponents.RSButtonFlat_new();
        BtnLibroDiario = new newscomponents.RSButtonFlat_new();
        BtnLibroMayor = new newscomponents.RSButtonFlat_new();
        BtnAgregarPartidas = new newscomponents.RSButtonFlat_new();
        BtnPeriodoContable = new newscomponents.RSButtonFlat_new();
        BtnGenerarBackup = new newscomponents.RSButtonFlat_new();
        BtnCatalogo = new newscomponents.RSButtonFlat_new();
        BtnCerrarSesion = new newscomponents.RSButtonFlat_new();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        escritorio.setBackground(new java.awt.Color(255, 255, 255));
        escritorio.setMinimumSize(new java.awt.Dimension(400, 1500));
        escritorio.setPreferredSize(new java.awt.Dimension(1000, 1000));
        escritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 102, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 0, 153));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 730));

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -20, 10, 730));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Sistema contable");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(153, 51, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        FondoJscroll.setBackground(new java.awt.Color(153, 102, 255));
        FondoJscroll.setPreferredSize(new java.awt.Dimension(100, 700));
        FondoJscroll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnBalanzaComprobacion.setBackground(new java.awt.Color(153, 102, 255));
        BtnBalanzaComprobacion.setForeground(new java.awt.Color(0, 0, 0));
        BtnBalanzaComprobacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Balanza.png"))); // NOI18N
        BtnBalanzaComprobacion.setText("Balanza de Comprobación");
        BtnBalanzaComprobacion.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnBalanzaComprobacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBalanzaComprobacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBalanzaComprobacionMouseClicked(evt);
            }
        });
        FondoJscroll.add(BtnBalanzaComprobacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 260, 40));

        BtnEstadoResultado.setBackground(new java.awt.Color(153, 102, 255));
        BtnEstadoResultado.setForeground(new java.awt.Color(0, 0, 0));
        BtnEstadoResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estadoResultado.png"))); // NOI18N
        BtnEstadoResultado.setText("Estado de Resultados");
        BtnEstadoResultado.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnEstadoResultado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnEstadoResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEstadoResultadoMouseClicked(evt);
            }
        });
        FondoJscroll.add(BtnEstadoResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 260, 30));

        BtnBalanzaGeneral.setBackground(new java.awt.Color(153, 102, 255));
        BtnBalanzaGeneral.setForeground(new java.awt.Color(0, 0, 0));
        BtnBalanzaGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BalanceGeneral.png"))); // NOI18N
        BtnBalanzaGeneral.setText("Balance General");
        BtnBalanzaGeneral.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnBalanzaGeneral.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBalanzaGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBalanzaGeneralMouseClicked(evt);
            }
        });
        FondoJscroll.add(BtnBalanzaGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 260, 30));

        BtnPartidaAjuste.setBackground(new java.awt.Color(153, 102, 255));
        BtnPartidaAjuste.setForeground(new java.awt.Color(0, 0, 0));
        BtnPartidaAjuste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PartidaAjuste.png"))); // NOI18N
        BtnPartidaAjuste.setText("Partidas de Ajuste");
        BtnPartidaAjuste.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnPartidaAjuste.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FondoJscroll.add(BtnPartidaAjuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 260, -1));

        BtnPartidasCierre.setBackground(new java.awt.Color(153, 102, 255));
        BtnPartidasCierre.setForeground(new java.awt.Color(0, 0, 0));
        BtnPartidasCierre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CierrePartidad.png"))); // NOI18N
        BtnPartidasCierre.setText("Partidas de Cierre");
        BtnPartidasCierre.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnPartidasCierre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FondoJscroll.add(BtnPartidasCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 230, -1));

        BtnCierreContable.setBackground(new java.awt.Color(153, 102, 255));
        BtnCierreContable.setForeground(new java.awt.Color(0, 0, 0));
        BtnCierreContable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CierreContable.png"))); // NOI18N
        BtnCierreContable.setText("Cierre Contable");
        BtnCierreContable.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnCierreContable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FondoJscroll.add(BtnCierreContable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 230, -1));

        BtnLibroDiario.setBackground(new java.awt.Color(153, 102, 255));
        BtnLibroDiario.setForeground(new java.awt.Color(0, 0, 0));
        BtnLibroDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libroDiario.png"))); // NOI18N
        BtnLibroDiario.setText("Libro Diario");
        BtnLibroDiario.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnLibroDiario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnLibroDiario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLibroDiarioMouseClicked(evt);
            }
        });
        FondoJscroll.add(BtnLibroDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 250, 30));

        BtnLibroMayor.setBackground(new java.awt.Color(153, 102, 255));
        BtnLibroMayor.setForeground(new java.awt.Color(0, 0, 0));
        BtnLibroMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregarLibroMayor.png"))); // NOI18N
        BtnLibroMayor.setText("Libro Mayor");
        BtnLibroMayor.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnLibroMayor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnLibroMayor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLibroMayorMouseClicked(evt);
            }
        });
        FondoJscroll.add(BtnLibroMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, 30));

        BtnAgregarPartidas.setBackground(new java.awt.Color(153, 102, 255));
        BtnAgregarPartidas.setForeground(new java.awt.Color(0, 0, 0));
        BtnAgregarPartidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-Partidad.png"))); // NOI18N
        BtnAgregarPartidas.setText("Agregar Partidas");
        BtnAgregarPartidas.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnAgregarPartidas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnAgregarPartidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarPartidasMouseClicked(evt);
            }
        });
        FondoJscroll.add(BtnAgregarPartidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, 30));

        BtnPeriodoContable.setBackground(new java.awt.Color(153, 102, 255));
        BtnPeriodoContable.setForeground(new java.awt.Color(0, 0, 0));
        BtnPeriodoContable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeriodoContable.png"))); // NOI18N
        BtnPeriodoContable.setText("Periodo Contable");
        BtnPeriodoContable.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnPeriodoContable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FondoJscroll.add(BtnPeriodoContable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 270, -1));

        BtnGenerarBackup.setBackground(new java.awt.Color(153, 102, 255));
        BtnGenerarBackup.setForeground(new java.awt.Color(0, 0, 0));
        BtnGenerarBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GenerarBackup.png"))); // NOI18N
        BtnGenerarBackup.setText("Generar backup");
        BtnGenerarBackup.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnGenerarBackup.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FondoJscroll.add(BtnGenerarBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 270, -1));

        BtnCatalogo.setBackground(new java.awt.Color(153, 102, 255));
        BtnCatalogo.setForeground(new java.awt.Color(0, 0, 0));
        BtnCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Catalogo.png"))); // NOI18N
        BtnCatalogo.setText("Catalogo");
        BtnCatalogo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnCatalogo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FondoJscroll.add(BtnCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 270, 40));

        jScrollPane1.setViewportView(FondoJscroll);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 270, 230));

        BtnCerrarSesion.setBackground(new java.awt.Color(153, 102, 255));
        BtnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        BtnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrarSesion.png"))); // NOI18N
        BtnCerrarSesion.setText("Cerrar Sesion");
        BtnCerrarSesion.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BtnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCerrarSesionMouseClicked(evt);
            }
        });
        jPanel2.add(BtnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 270, 50));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ahorrar-dinero.png"))); // NOI18N
        jPanel7.add(jLabel2);

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 110, 80));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Sistema contable");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 200, 30));

        escritorio.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 1030));

        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(102, 0, 153));
        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(102, 0, 153));
        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBackground(new java.awt.Color(102, 0, 153));
        getContentPane().add(jPanel6, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarSesionMouseClicked
           exit(0);
    }//GEN-LAST:event_BtnCerrarSesionMouseClicked

    private void BtnAgregarPartidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarPartidasMouseClicked
        // Vista crear partida
      Vista.CrearPartida vista = new Vista.CrearPartida();    
      Controlador.CrearPartidaControlador ctrl = new Controlador.CrearPartidaControlador(vista);
      vista.setVisible(true);
    }//GEN-LAST:event_BtnAgregarPartidasMouseClicked

    private void BtnLibroDiarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLibroDiarioMouseClicked
       //Vista libro diario
        Vista.LibroDiario vistaLD = new Vista.LibroDiario();
        Controlador.LibroDiarioControlador ctrl = new Controlador.LibroDiarioControlador(vistaLD);
        vistaLD.setVisible(true);

    }//GEN-LAST:event_BtnLibroDiarioMouseClicked

    private void BtnEstadoResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEstadoResultadoMouseClicked
       Vista.EstadoDeResultado vista = new Vista.EstadoDeResultado();
       Controlador.EstadoDeResultadoControlador ctr = new EstadoDeResultadoControlador(vista);
       vista.setVisible(true);
    }//GEN-LAST:event_BtnEstadoResultadoMouseClicked

    private void BtnBalanzaComprobacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBalanzaComprobacionMouseClicked
       Vista.BalanzaComprobacion vista = new BalanzaComprobacion();
       Controlador.BalanzaComprobacionControlador ctr = new BalanzaComprobacionControlador(vista);
       vista.setVisible(true);
    }//GEN-LAST:event_BtnBalanzaComprobacionMouseClicked

    private void BtnLibroMayorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLibroMayorMouseClicked
        Vista.LibroMayor vista = new LibroMayor();
        Controlador.LibroMayorControlador ctr = new LibroMayorControlador(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_BtnLibroMayorMouseClicked

    private void BtnBalanzaGeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBalanzaGeneralMouseClicked
      Vista.BalanceGeneral vista = new BalanceGeneral();
      Controlador.BalanceGeneralControlador ctr = new BalanceGeneralControlador(vista);
      vista.setVisible(true);
    }//GEN-LAST:event_BtnBalanzaGeneralMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public newscomponents.RSButtonFlat_new BtnAgregarPartidas;
    public newscomponents.RSButtonFlat_new BtnBalanzaComprobacion;
    public newscomponents.RSButtonFlat_new BtnBalanzaGeneral;
    public newscomponents.RSButtonFlat_new BtnCatalogo;
    public newscomponents.RSButtonFlat_new BtnCerrarSesion;
    public newscomponents.RSButtonFlat_new BtnCierreContable;
    public newscomponents.RSButtonFlat_new BtnEstadoResultado;
    public newscomponents.RSButtonFlat_new BtnGenerarBackup;
    public newscomponents.RSButtonFlat_new BtnLibroDiario;
    public newscomponents.RSButtonFlat_new BtnLibroMayor;
    public newscomponents.RSButtonFlat_new BtnPartidaAjuste;
    public newscomponents.RSButtonFlat_new BtnPartidasCierre;
    public newscomponents.RSButtonFlat_new BtnPeriodoContable;
    private javax.swing.JPanel FondoJscroll;
    public javax.swing.JPanel escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
